services:
    common_entity_class.constraint_generator_helper:
        class: Floaush\Bundle\CommonEntityClass\Annotation\Helper\ConstraintGeneratorHelper
        arguments:
            - "@annotations.reader"
    common_entity_class.constraint_generator_subscriber:
        class: Floaush\Bundle\CommonEntityClass\EventListener\ConstraintGeneratorSubscriber
        arguments:
            - "@common_entity_class.constraint_generator_helper"
            - "@validator"